name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Or the branch you want to trigger this action

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t learnwithraghu/k8-workshop:v1 .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push learnwithraghu/k8-workshop:v1
